### ISSUE TITLE
FYI Official Ollama Python Library

### ISSUE THREAD

**Issue by easp** [taketwo/llm-ollama#1]
Thanks for doing this!

FYI, the Ollama project recently posted their own official python library:
https://github.com/jmorganca/ollama-python

**Comment by taketwo** [comment]
Thanks for the feedback. Yeah, I bumped into this library just after I finished implementing the plugin. It's not much work to switch to using it, but I'm not sure if there are advantages.

**Comment by taketwo** [comment]
I've updated the plugin to use the library.
