### ISSUE TITLE
Expose `format="json"`? 

### ISSUE THREAD

**Issue by jefftriplett** [taketwo/llm-ollama#12]
Would it be possible to expose python-ollama's `format` argument so we can output JSON from the plugin? 

I was reading up on https://whoa.fyi/how-to-get-json-response-from-ollama/ last night when I discovered that getting JSON out of Ollama was much easier than my previous attempts. 

The possible options seem to be `["", "json"]`.

**Comment by jefftriplett** [comment]
Ideally, you'd expose it to the `ollama.chat` calls. See https://github.com/ollama/ollama-python/blob/f62eb97a4a736fffcfc5a4cf30ae8b4dda937967/ollama/_client.py#L189 for an example. 

I haven't forked and tested it out, but I'd love to be able to get json back from llm+llm-ollama when using ollama models. I use this option when I call when I'm using the `ollama-python` library directly.

**Comment by taketwo** [comment]
I've just tagged a new release that includes support for this feature.

> Additionally, the -o json_object 1 option can be used to force the model to reply with a valid JSON object. Note that your prompt must mention JSON for this to work.

**Comment by jefftriplett** [comment]
@taketwo yay, danke.
