### ISSUE TITLE
Support for embedding models installed through Ollama

### ISSUE THREAD

**Issue by javierhb23** [taketwo/llm-ollama#14]
The llm library offers support for working with embedding models through plugins such as [llm sentence transformers](https://github.com/simonw/llm-sentence-transformers)
I'm curious to know if there are plans for adding support for [embedding models installed through Ollama](https://ollama.com/blog/embedding-models) (e.g.: `ollama pull mxbai-embed-large`) for this project, or whether this would be provided by a separate plugin altogether?
Edit: Sorry, I just noticed the [embed](https://github.com/taketwo/llm-ollama/tree/embed) branch, looks like it's a wip. Feel free to close this issue.

**Comment by taketwo** [comment]
Yes, I did an experiment, and I think it worked, but I've never finished and merged it. Currently, I don't have a personal use case for this, so it's not on my list. But contributions are always welcome!

**Comment by sukhbinder** [comment]
Saw this today. I have added support for the Ollama embedding models as a separate plugin with [llm-embed-ollama](https://github.com/sukhbinder/llm-embed-ollama)

**Comment by javierhb23** [comment]
Cool! Thanks @sukhbinder, I'll check it out. Closing 👍
